#include "ImgUtils.h"


void print_image_header(image_header* hdr) {
	printf("Image Header:: type=%c, rows=%d, cols=%d, maxval=%d, pgmraw=%d\n", 
		hdr->type, hdr->rows, hdr->cols, hdr->maxval, hdr->pgmraw);
}


gs_image* read_image(const char* filename)
{
	gray* graymap;
	int ich1, ich2, rows, cols, maxval=255, pgmraw;
	int i, j;

	FILE* ifp = fopen(filename, "r");
	if (ifp == NULL) {
		printf("error in opening file %s\n", filename);
		exit(1);
	}

	/*  Magic number reading */
	ich1 = getc( ifp );
	if (ich1 == EOF)
		pm_erreur( "EOF / read error / magic number" );
	ich2 = getc( ifp );
	if ( ich2 == EOF )
		pm_erreur( "EOF /read error / magic number" );
	if(ich2 != '2' && ich2 != '5')
		pm_erreur(" wrong file type ");
	
	if (ich2 == '2') pgmraw = 0;
	else pgmraw = 1;

	/* Reading image dimensions */
	cols = pm_getint(ifp);
	rows = pm_getint(ifp);
	if (ich2 != '1')
		maxval = pm_getint(ifp);

	image_header* hdr = malloc(sizeof(image_header));
	hdr->type = ich2;
	hdr->cols = cols;
	hdr->rows = rows;
	hdr->maxval = maxval;
	hdr->pgmraw = pgmraw;

	/* Memory allocation  */
	graymap = (gray *) malloc(cols * rows * sizeof(gray));

	/* Reading */
	for(i=0; i < rows; i++)
		for(j=0; j < cols ; j++)
		if(pgmraw)
			graymap[i * cols + j] = pm_getrawbyte(ifp) ;
		else
			graymap[i * cols + j] = pm_getint(ifp);
	
	fclose(ifp);

	gs_image* img = malloc(sizeof(gs_image));
	img->hdr = hdr;
	img->data = graymap;
	return img;
}

void write_image(const char* filename, gs_image* img)
{
	FILE *ifp = fopen(filename, "w");
	if (!ifp) {
		exit(1);
	}
	image_header* hdr = img->hdr;
	fprintf(ifp, "P%c\n", hdr->type);
	fprintf(ifp, "# %s\n", "This image is generated by Jad & Shubham");
	fprintf(ifp, "%d %d\n", hdr->cols, hdr->rows);
	fprintf(ifp, "%d\n", hdr->maxval);

	int i,j;
	for(i=0; i < hdr->rows; i++)
		for(j=0; j < hdr->cols; j++)
			fprintf(ifp, hdr->pgmraw ? "%c" : "%d ", 
				img->data[i * hdr->cols + j]);

	fclose(ifp);
}